"""Conformance classes published by the OGC API standards.

GENERATED by scripts/harvest_conformance_classes.py — do not edit by
hand. Each entry records the OGC document it was read from, so a
claim in this file can be checked against the text that makes it.

What is deliberately *not* here: whether a class is mandatory. That
is not a property of the URI and no machine-readable source states
it; it follows from each standard's dependency graph, and getting
it wrong is how a validator comes to report a compliant server as
non-compliant. It is added per class, with the clause that
justifies it, as each standard is read.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class KnownConformanceClass:
    """A conformance class URI a published standard defines."""

    uri: str
    spec: str
    version: str
    name: str
    document: str


#: The OGC documents this catalogue was read from.
SOURCE_DOCUMENTS: dict[str, str] = {
    "17-069r4": "OGC API - Features - Part 1: Core",
    "18-058r1": "OGC API - Features - Part 2: Coordinate Reference Systems by Reference",
    "18-062r2": "OGC API - Processes - Part 1: Core",
    "19-079r2": "OGC API - Features - Part 3: Filtering",
    "19-086r6": "OGC API - Environmental Data Retrieval",
    "20-057": "OGC API - Tiles - Part 1: Core",
    "20-058": "OGC API - Maps - Part 1: Core",
}

KNOWN_CONFORMANCE_CLASSES: dict[str, KnownConformanceClass] = {
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/collections": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/collections",
        spec="ogcapi-edr-1",
        version="1.1",
        name="collections",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/core": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/core",
        spec="ogcapi-edr-1",
        version="1.1",
        name="core",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/covjson": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/covjson",
        spec="ogcapi-edr-1",
        version="1.1",
        name="covjson",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/edr-geojson": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/edr-geojson",
        spec="ogcapi-edr-1",
        version="1.1",
        name="edr-geojson",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/geojson": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/geojson",
        spec="ogcapi-edr-1",
        version="1.1",
        name="geojson",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/html": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/html",
        spec="ogcapi-edr-1",
        version="1.1",
        name="html",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/json": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/json",
        spec="ogcapi-edr-1",
        version="1.1",
        name="json",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/oas30": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/oas30",
        spec="ogcapi-edr-1",
        version="1.1",
        name="oas30",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/queries": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/queries",
        spec="ogcapi-edr-1",
        version="1.1",
        name="queries",
        document="19-086r6",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
        spec="ogcapi-features-1",
        version="1.0",
        name="core",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson",
        spec="ogcapi-features-1",
        version="1.0",
        name="geojson",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0",
        spec="ogcapi-features-1",
        version="1.0",
        name="gmlsf0",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2",
        spec="ogcapi-features-1",
        version="1.0",
        name="gmlsf2",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html",
        spec="ogcapi-features-1",
        version="1.0",
        name="html",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
        spec="ogcapi-features-1",
        version="1.0",
        name="oas30",
        document="17-069r4",
    ),
    "http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs",
        spec="ogcapi-features-2",
        version="1.0",
        name="crs",
        document="18-058r1",
    ),
    "http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter",
        spec="ogcapi-features-3",
        version="1.0",
        name="features-filter",
        document="19-079r2",
    ),
    "http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter",
        spec="ogcapi-features-3",
        version="1.0",
        name="filter",
        document="19-079r2",
    ),
    "http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables",
        spec="ogcapi-features-3",
        version="1.0",
        name="queryables",
        document="19-079r2",
    ),
    "http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables-query-parameters": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables-query-parameters",
        spec="ogcapi-features-3",
        version="1.0",
        name="queryables-query-parameters",
        document="19-079r2",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations",
        spec="ogcapi-maps-1",
        version="1.0",
        name="api-operations",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background",
        spec="ogcapi-maps-1",
        version="1.0",
        name="background",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map",
        spec="ogcapi-maps-1",
        version="1.0",
        name="collection-map",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection",
        spec="ogcapi-maps-1",
        version="1.0",
        name="collections-selection",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core",
        spec="ogcapi-maps-1",
        version="1.0",
        name="core",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors",
        spec="ogcapi-maps-1",
        version="1.0",
        name="cors",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs",
        spec="ogcapi-maps-1",
        version="1.0",
        name="crs",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map",
        spec="ogcapi-maps-1",
        version="1.0",
        name="dataset-map",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime",
        spec="ogcapi-maps-1",
        version="1.0",
        name="datetime",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution",
        spec="ogcapi-maps-1",
        version="1.0",
        name="display-resolution",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting",
        spec="ogcapi-maps-1",
        version="1.0",
        name="general-subsetting",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html",
        spec="ogcapi-maps-1",
        version="1.0",
        name="html",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg",
        spec="ogcapi-maps-1",
        version="1.0",
        name="jpeg",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl",
        spec="ogcapi-maps-1",
        version="1.0",
        name="jpegxl",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation",
        spec="ogcapi-maps-1",
        version="1.0",
        name="orientation",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png",
        spec="ogcapi-maps-1",
        version="1.0",
        name="png",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection",
        spec="ogcapi-maps-1",
        version="1.0",
        name="projection",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling",
        spec="ogcapi-maps-1",
        version="1.0",
        name="scaling",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting",
        spec="ogcapi-maps-1",
        version="1.0",
        name="spatial-subsetting",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map",
        spec="ogcapi-maps-1",
        version="1.0",
        name="styled-map",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg",
        spec="ogcapi-maps-1",
        version="1.0",
        name="svg",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff",
        spec="ogcapi-maps-1",
        version="1.0",
        name="tiff",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets",
        spec="ogcapi-maps-1",
        version="1.0",
        name="tilesets",
        document="20-058",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback",
        spec="ogcapi-processes-1",
        version="1.0",
        name="callback",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core",
        spec="ogcapi-processes-1",
        version="1.0",
        name="core",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss",
        spec="ogcapi-processes-1",
        version="1.0",
        name="dismiss",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html",
        spec="ogcapi-processes-1",
        version="1.0",
        name="html",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list",
        spec="ogcapi-processes-1",
        version="1.0",
        name="job-list",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json",
        spec="ogcapi-processes-1",
        version="1.0",
        name="json",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30",
        spec="ogcapi-processes-1",
        version="1.0",
        name="oas30",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description",
        spec="ogcapi-processes-1",
        version="1.0",
        name="ogc-process-description",
        document="18-062r2",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/collections-selection": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/collections-selection",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="collections-selection",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="core",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="dataset-tilesets",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/datetime": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/datetime",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="datetime",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="geodata-tilesets",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geojson": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geojson",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="geojson",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/jpeg": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/jpeg",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="jpeg",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/mvt": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/mvt",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="mvt",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/netcdf": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/netcdf",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="netcdf",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/oas30": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/oas30",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="oas30",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/png": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/png",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="png",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tiff": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tiff",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="tiff",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="tileset",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="tilesets-list",
        document="20-057",
    ),
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/xml": KnownConformanceClass(
        uri="http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/xml",
        spec="ogcapi-tiles-1",
        version="1.0",
        name="xml",
        document="20-057",
    ),
}
