"""Harvest conformance class URIs from the published OGC API standards.

The catalogue in `ogcapi_registry.known_classes` is generated by this
script rather than typed by hand, so every entry can be traced to the
document that defines it and the whole thing can be refreshed when a
standard is revised.

    uv run python scripts/harvest_conformance_classes.py

Two details the extraction has to get right, both learned by getting
them wrong first:

* The scheme is not uniform. Most standards write
  `http://www.opengis.net/spec/...`; OGC API - Maps writes `https://`.
  Matching only the first silently yields nothing for that standard.
* `…/conf/collections/rc-md-success` is a *requirement* identifier, not
  a conformance class. A class name carries no slash.

A standard also cites classes belonging to others — Tiles refers to
Common — and those are attributed to the standard that defines them, not
to the one doing the citing.
"""

from __future__ import annotations

import html
import re
import urllib.request
from pathlib import Path

#: The published standards this catalogue covers, as OGC document
#: numbers, with the conformance class prefix each one defines.
DOCUMENTS: dict[str, tuple[str, str]] = {
    "17-069r4": ("ogcapi-features-1", "OGC API - Features - Part 1: Core"),
    "18-058r1": (
        "ogcapi-features-2",
        "OGC API - Features - Part 2: Coordinate Reference Systems by Reference",
    ),
    "19-079r2": ("ogcapi-features-3", "OGC API - Features - Part 3: Filtering"),
    "20-057": ("ogcapi-tiles-1", "OGC API - Tiles - Part 1: Core"),
    "18-062r2": ("ogcapi-processes-1", "OGC API - Processes - Part 1: Core"),
    "19-086r6": ("ogcapi-edr-1", "OGC API - Environmental Data Retrieval"),
    "20-058": ("ogcapi-maps-1", "OGC API - Maps - Part 1: Core"),
}

CONFORMANCE_URI = re.compile(
    r"https?://www\.opengis\.net/spec/(ogcapi-[a-z]+-\d+)/(\d+\.\d+)/conf/"
    r"([a-z0-9][a-z0-9-]*)(?![a-z0-9/-])"
)


def text_of(document: str, cache: Path) -> str:
    """The standard's HTML, stripped to text, fetched once."""
    local = cache / f"{document}.html"
    if not local.exists():
        url = f"https://docs.ogc.org/is/{document}/{document}.html"
        with urllib.request.urlopen(url) as response:  # noqa: S310 - fixed host
            local.write_bytes(response.read())
    raw = local.read_text(errors="ignore")
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", raw)))


def harvest(cache: Path) -> dict[str, tuple[str, str, str, str]]:
    """Map each conformance class URI to (spec, version, name, document)."""
    catalogue: dict[str, tuple[str, str, str, str]] = {}
    for document, (prefix, _title) in DOCUMENTS.items():
        body = text_of(document, cache)
        for match in CONFORMANCE_URI.finditer(body):
            spec, version, name = match.groups()
            if spec != prefix:
                continue
            uri = f"http://www.opengis.net/spec/{spec}/{version}/conf/{name}"
            catalogue.setdefault(uri, (spec, version, name, document))
    return catalogue


def render(catalogue: dict[str, tuple[str, str, str, str]]) -> str:
    """The generated module, ordered so a diff stays readable."""
    lines = [
        '"""Conformance classes published by the OGC API standards.',
        "",
        "GENERATED by scripts/harvest_conformance_classes.py — do not edit by",
        "hand. Each entry records the OGC document it was read from, so a",
        "claim in this file can be checked against the text that makes it.",
        "",
        "What is deliberately *not* here: whether a class is mandatory. That",
        "is not a property of the URI and no machine-readable source states",
        "it; it follows from each standard's dependency graph, and getting",
        "it wrong is how a validator comes to report a compliant server as",
        "non-compliant. It is added per class, with the clause that",
        "justifies it, as each standard is read.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class KnownConformanceClass:",
        '    """A conformance class URI a published standard defines."""',
        "",
        "    uri: str",
        "    spec: str",
        "    version: str",
        "    name: str",
        "    document: str",
        "",
        "",
        "#: The OGC documents this catalogue was read from.",
        "SOURCE_DOCUMENTS: dict[str, str] = {",
    ]
    for document, (_prefix, title) in sorted(DOCUMENTS.items()):
        lines.append(f'    "{document}": "{title}",')
    lines += [
        "}",
        "",
        "KNOWN_CONFORMANCE_CLASSES: dict[str, KnownConformanceClass] = {",
    ]
    for uri, (spec, version, name, document) in sorted(catalogue.items()):
        lines.append(
            f'    "{uri}": KnownConformanceClass(\n'
            f'        uri="{uri}",\n'
            f'        spec="{spec}",\n'
            f'        version="{version}",\n'
            f'        name="{name}",\n'
            f'        document="{document}",\n'
            f"    ),"
        )
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> None:
    cache = Path(".cache/ogc-standards")
    cache.mkdir(parents=True, exist_ok=True)
    catalogue = harvest(cache)
    target = Path("src/ogcapi_registry/known_classes.py")
    target.write_text(render(catalogue))
    print(f"{len(catalogue)} classes from {len(DOCUMENTS)} documents -> {target}")


if __name__ == "__main__":
    main()
